=== gouthampacha/interop/doc/source/schema/2.0.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "id": "http://git.openstack.org/cgit/openstack/interop/doc/source/schema/2.0.json",
  "type": "object",
  "properties": {
    "metadata": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "schema": {
          "type": "string"
        },
        "reference": {
          "type": "string"
        },
        "source": {
          "type": "string"
        },
        "scoring": {
          "type": "object",
          "properties": {
            "cutoff_score": {
              "type": "integer"
            },
            "criteria": {
              "type": "object",
              "patternProperties": {
                "^[A-Za-z0-9_-]+": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "weight": {
                      "type": "integer"
                    }
                  },
                  "required": [
                    "name",
                    "description",
                    "weight"
                  ]
                }
              }
            }
          }
        },
        "os_trademark_approval": {
          "type": "object",
          "properties": {
            "target_approval": {
              "type": "string",
              "pattern": "\\d\\d\\d\\d.\\d\\d"
            },
            "replaces": {
              "type": "string",
              "pattern": "\\d\\d\\d\\d.\\d\\d"
            },
            "releases": {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "string"
              },
              "uniqueItems": true
            },
            "status": {
              "enum": ["draft", "advisory", "approved", "superceded"]
            }
          },
          "required": [
            "target_approval",
            "releases",
            "status"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "id",
        "schema",
        "reference",
        "source"
      ],
      "additionalProperties": true
    },
    "platforms": {
      "type": "object",
      "patternProperties": {
        "^\\w+$": {
          "type": "object",
          "additionalProperties": false,
          "required": [ "components" ],
          "properties": {
            "description": { "type": "string" },
            "components": {
              "$ref": "#/definitions/component_reference",
              "type": "array",
              "items": {
                "type": "object",
                "required": ["name"],
                "additionalProperties": false,
                "properties": {
                  "source": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "extensions": {
      "type": "object",
      "patternProperties": {
        "^\\w+$": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "description": { "type": "string" },
            "components": {
              "$ref": "#/definitions/component_reference",
              "type": "array",
              "items": {
                "type": "object",
                "required": ["name"],
                "additionalProperties": false,
                "properties": {
                  "source": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  }
                }
              }
            },
            "required_platform_components": {
              "$ref": "#/definitions/component_reference",
              "type": "array",
              "items": {
                "type": "object",
                "required": ["name"],
                "additionalProperties": false,
                "properties": {
                  "source": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  }
                }
              }
            },
            "optional_platform_components": {
              "$ref": "#/definitions/component_reference",
              "type": "array",
              "items": {
                "type": "object",
                "required": ["name"],
                "additionalProperties": false,
                "properties": {
                  "source": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "components": {
      "type": "object",
      "patternProperties": {
        "^\\w+$": {
          "type": "object",
          "patternProperties": {
            "capabilities|designated_sections": {
              "type": "object",
              "additionalProperties": false,
              "patternProperties": {
                "required|advisory|deprecated|removed": {
                  "type": "array",
                  "items": { "type": "string" }
                }
              }
            }
          }
        }
      }
    },
    "capabilities": {
      "type": "object",
      "patternProperties": {
        "^\\w+$": {
          "type": "object",
          "properties": {
            "achievements": {
              "type": "array",
              "items": { "type": "string" },
              "uniqueItems": true
            },
            "admin": { "type": "boolean" },
            "required_since": {
              "type": "string",
              "pattern": "\\d\\d\\d\\d.\\d\\d"
            },
            "description": { "type": "string" },
            "tests": {
              "type": "object",
              "patternProperties": {
                "^\\w+$": {
                  "type": "object",
                  "required": [ "idempotent_id" ],
                  "properties": {
                    "idempotent_id": { "type": "string" },
                    "aliases": {
                      "type": "array",
                      "items": { "type": "string" },
                      "minItems": 1,
                      "uniqueItems": true
                    },
                    "flag": {
                      "type": "object",
                      "required": [ "reason", "action", "date" ],
                      "properties": {
                        "reason": {
                          "type": "string",
                          "pattern": "^D\\d{3} \\w+"
                        },
                        "action": {
                          "type": "string"
                        },
                        "date": {
                          "type": "string",
                          "pattern": "\\d{4}-\\d{2}-\\d{2}"
                        }
                      }
                    }
                  }
                }
              }
            },
            "project": {
              "type": "string"
            }
          },
          "required": [
            "achievements",
            "admin",
            "description",
            "project",
            "tests"
          ],
          "additionalProperties": false
        }
      }
    },
    "designated_sections": {
      "type": "object",
      "patternProperties": {
        "^\\w+$": {
          "type": "object",
          "patternProperties": {
            "required|advisory|deprecated|removed|informational": {
              "type": "object",
              "required": [ "guidance", "sections"],
              "properties": {
                "guidance": {
                  "type": "string"
                },
                "comment": {
                  "type": "string"
                },
                "sections": {
                  "type": "object",
                  "patternProperties": {
                    "^\\w+$": {
                      "type": "object",
                      "required": ["description", "designated"],
                      "properties": {
                        "description": {
                          "type": "string"
                        },
                        "designated": {
                          "type": "boolean"
                        },
                        "comment": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "test_repositories": {
      "type": "object",
      "patternProperties": {
        "^\\w+$": {
          "type": "object",
          "additionalProperties": false,
          "required": [ "repository" ],
          "properties": {
            "repository": { "type": "string" },
            "reference": { "type": "string" },
            "description": { "type": "string" }
          }
        }
      }
    }
  },
  "required": [
    "metadata",
    "components",
    "capabilities",
    "designated_sections",
    "test_repositories"
  ],
  "additionalProperties": false,
  "definitions": {
    "component_reference": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [ "name" ],
        "additionalProperties": false,
        "properties": {
          "name": { "type": "string" },
          "source": { "type": "string"
          }
        }
      }
    }
  }
}

=== gouthampacha/interop/verticals/nfv.next.json
{
  "metadata": {
    "id": "nfv.next",
    "schema": "2.0",
    "reference": "https://git.openstack.org/cgit/openstack/interop/schema/2.0.json",
    "source": "http://git.openstack.org/cgit/openstack/interop/",
    "scoring": {
      "cutoff_score": 74,
      "criteria": {
        "atomic": {
          "name": "Atomic",
          "description": "The capabilities are unique and cannot be built out of other must-pass capabilities.",
          "weight": 6
        },
        "clients": {
          "name": "Used By Clients",
          "description": "The capabilities are widely used by common OpenStack clients, including the openstack client, nova client, neutron client, and so on. This criterion pertains mostly to API versioning. For example, if v2 of a given API is not used by other OpenStack clients but v1 is, then v2 doesn't achieve the 'used by clients' criterion.",
          "weight": 10
        },
        "complete": {
          "name": "Complete",
          "description": "Where the code being tested has a designated area of alternate implementation (extension framework) as per the Core Principles, there should be parity in capability tested across extension implementations. This also implies that the capability test is not configuration specific or locked to non-open technology.",
          "weight": 8
        },
        "deployed": {
          "name": "Widely Deployed",
          "description": "The capabilities are widely deployed capabilities. We favor capabilities that are supported by multiple public cloud providers and private cloud products.",
          "weight": 8
        },
        "discover": {
          "name": "Discoverable",
          "description": "Capability being tested is Service Discoverable (can be found in Keystone and via service introspection).",
          "weight": 8
        },
        "doc": {
          "name": "Documented",
          "description": "The capability is well documented, including both the interface and the expected behavior.",
          "weight": 8
        },
        "foundation": {
          "name": "Foundation",
          "description": "The capability is a fundamental requirement for must-pass tests, or is depended on by other capabilities.",
          "weight": 9
        },
        "future": {
          "name": "Future Direction",
          "description": "The capability reflects the future technical direction as defined by theproject technical teams and the Technical Committee.",
          "weight": 11
        },
        "proximity": {
          "name": "Proximity Cluster",
          "description": "A capability that is related to another set of core capabilitity. The intent is to ensure that related capabilities are selected for and managed together.",
          "weight": 8
        },
        "stable": {
          "name": "Stable",
          "description": "A capability whose API has not changed in more than two releases. Meant to select for capabilities that are stable and not under active development.",
          "weight": 9
        },
        "sticky": {
          "name": "Core In Last Release",
          "description": "A capability whose API was present in the previous guideline release. Discourages the disruption of replacing the API a capability uses, or removing a capability from core.",
          "weight": 9
        },
        "tools": {
          "name": "Used By Tools",
          "description": "Capabilities that are widely used outside of the OpenStack client ecosystem. Example tools include GopherCloud, jClouds, Fog, and so on.",
          "weight": 6
        }
      }
    },
    "os_trademark_approval": {
      "target_approval": "2018.02",
      "releases": ["newton", "ocata", "pike", "queens"],
      "status": "draft"
    }
  },
  "platforms": {
    "OpenStack Powered NFV Platform": {
      "description": "OpenStack services targeting NFV use cases including identity, compute, networking, block storage, and NFV capabilities.",
      "components": [
        {
          "name": "os_powered_nfv_platform"
        },
        {
          "name": "os_powered_compute",
          "source": "https://git.openstack.org/cgit/openstack/interop/tree/2017.09.json"
        }
      ]
    }
  },
  "components": {
    "os_powered_nfv_platform": {
      "capabilities": {
        "required": [
        ],
        "advisory": [
          "networking-trunk-port-crud",
          "networking-trunk-subport-crud",
          "networking-trunk-show-trunk-details",
          "networking-bgpvpn-bgpvpn-crud",
          "networking-bgpvpn-net-assoc-crud",
          "networking-bgpvpn-router-assoc-crud"
        ],
        "deprecated": [
        ],
        "removed": [
        ]
      },
      "designated_sections": {
        "required": [
          "nova",
          "keystone",
          "glance",
          "neutron",
          "cinder"
        ]
      }
    }
  },
  "capabilities": {
    "networking-trunk-port-crud": {
      "achievements": [
        "complete",
        "doc",
        "proximity",
        "clients",
        "discover",
        "future",
        "atomic",
        "stable",
        "deployed"
      ],
      "admin": false,
      "description": "CRUD operations for VLAN trunk ports",
      "project": "neutron",
      "tests": {
        "neutron.tests.tempest.api.test_trunk.test_create_trunk_empty_subports_list": {
          "idempotent_id": "id-e1a6355c-4768-41f3-9bf8-0f1d192bd501"
        },
        "neutron.tests.tempest.api.test_trunk.test_create_trunk_subports_not_specified": {
          "idempotent_id": "id-382dfa39-ca03-4bd3-9a1c-91e36d2e3796"
        },
        "neutron.tests.tempest.api.test_trunk.test_create_show_delete_trunk": {
          "idempotent_id": "id-7de46c22-e2b6-4959-ac5a-0e624632ab32"
        },
        "neutron.tests.tempest.api.test_trunk.test_create_update_trunk": {
          "idempotent_id": "id-4ce46c22-a2b6-4659-bc5a-0ef2463cab32"
        },
        "neutron.tests.tempest.api.test_trunk.test_create_update_trunk_with_description": {
          "idempotent_id": "id-5ff46c22-a2b6-5559-bc5a-0ef2463cab32"
        },
        "neutron.tests.tempest.api.test_trunk.test_list_trunks": {
          "idempotent_id": "id-73365f73-bed6-42cd-960b-ec04e0c99d85"
        },
        "neutron.tests.tempest.api.test_trunk.test_delete_trunk_with_subport_is_allowed": {
          "idempotent_id": "id-ee5fcead-1abf-483a-bce6-43d1e06d6aa0"
        }
      }
    },
    "networking-trunk-subport-crud": {
      "achievements": [
        "complete",
        "doc",
        "proximity",
        "clients",
        "discover",
        "future",
        "atomic",
        "stable",
        "deployed"
      ],
      "admin": false,
      "description": "CRUD operations for VLAN trunk subports",
      "project": "neutron",
      "tests": {
        "neutron.tests.tempest.api.test_trunk.test_add_subport": {
          "idempotent_id": "id-bb5fcead-09b5-484a-bbe6-46d1e06d6cc0"
        },
        "neutron.tests.tempest.api.test_trunk.test_remove_subport": {
          "idempotent_id": "id-96eea398-a03c-4c3e-a99e-864392c2ca53"
        },
        "neutron.tests.tempest.api.test_trunk.test_get_subports": {
          "idempotent_id": "id-bb5fcaad-09b5-484a-dde6-4cd1ea6d6ff0"
        }
      }
    },
    "networking-trunk-show-trunk-details": {
      "achievements": [
        "complete",
        "doc",
        "proximity",
        "clients",
        "discover",
        "future",
        "atomic",
        "stable",
        "deployed"
      ],
      "admin": false,
      "description": "Retrieve trunk_details extension attribute when showing a port resource that participates in a trunk as parent",
      "project": "neutron",
      "tests": {
        "neutron.tests.tempest.api.test_trunk_details.test_port_resource_trunk_details_no_subports": {
          "idempotent_id": "id-f0bed24f-d36a-498b-b4e7-0d66e3fb7308"
        },
        "neutron.tests.tempest.api.test_trunk_details.test_port_resource_trunk_details_with_subport": {
          "idempotent_id": "id-544bcaf2-86fb-4930-93ab-ece1c3cc33df"
        },
        "neutron.tests.tempest.api.test_trunk_details.test_port_resource_empty_trunk_details": {
          "idempotent_id": "id-fe6d865f-1d5c-432e-b65d-904157172f24"
        }
      }
    },
    "networking-bgpvpn-bgpvpn-crud": {
      "achievements": [
        "complete",
        "doc",
        "proximity",
        "clients",
        "discover",
        "future",
        "atomic",
        "stable",
        "tools",
        "deployed"
      ],
      "admin": true,
      "description": "CRUD operations for BGP VPNs",
      "project": "networking-bgpvpn",
      "tests": {
        "networking_bgpvpn_tempest.tests.api.test_bgpvpn.test_create_bgpvpn": {
          "idempotent_id": "id-4f90deb2-eb8e-4e7d-9d68-c5b5cc657f7e"
        },
        "networking_bgpvpn_tempest.tests.api.test_bgpvpn.test_create_bgpvpn_as_non_admin_fail": {
          "idempotent_id": "id-0a911d61-d908-4c21-a11e-e403ac0d8e38"
        },
        "networking_bgpvpn_tempest.tests.api.test_bgpvpn.test_create_bgpvpn_with_invalid_routetargets": {
          "idempotent_id": "id-464ca6f9-86e4-4ee3-9c65-f1edae93223d"
        },
        "networking_bgpvpn_tempest.tests.api.test_bgpvpn.test_delete_bgpvpn": {
          "idempotent_id": "id-709b23b0-9719-47df-9f53-b0812a5d5a48"
        },
        "networking_bgpvpn_tempest.tests.api.test_bgpvpn.test_delete_bgpvpn_as_non_admin_fail": {
          "idempotent_id": "id-596abfc2-fd89-491d-863d-25459db1df4b"
        },
        "networking_bgpvpn_tempest.tests.api.test_bgpvpn.test_show_bgpvpn_as_non_owner_fail": {
          "idempotent_id": "id-b20110bb-393b-4342-8b30-6486cd2b4fc6"
        },
        "networking_bgpvpn_tempest.tests.api.test_bgpvpn.test_list_bgpvpn": {
          "idempotent_id": "id-7a7feca2-1c24-4f5d-ad4b-b0e5a712adb1"
        },
        "networking_bgpvpn_tempest.tests.api.test_bgpvpn.test_list_bgpvpn_as_non_owner_fail": {
